services:

  tg_bot:
    build: .
    container_name: tg_bot
    env_file:
      - .env
    ports:
      - "8004:8000"
    volumes:
      - .:/app
    networks:
      - ngrok

  ngrok:
    image: wernight/ngrok
    container_name: ngrok
    ports:
      - "4040:4040"  # For ngrok web interface
    env_file:
      - .env
    command: ["ngrok", "http", "tg_bot:8000"]
    networks:
      - ngrok


networks:
  ngrok:
    driver: bridge
