services:

  bot:
    build: .
    container_name: bot
    env_file:
      - .env
    ports:
      - "8004:8000"
    volumes:
      - .:/app
    networks:
      - app-network

  tma:
    build:
      context: ./tma
    ports:
      - "3000:3000"
    env_file:
      - ./tma/.env.local
    networks:
      - app-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - app-network

  ngrok:
    image: wernight/ngrok
    container_name: bot-ngrok
    ports:
      - "4040:4040"  # For ngrok web interface
    env_file:
      - .env
    command: ["ngrok", "http", "bot:8000"]
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
